export type CountryEntry = {
  code: string;
  en: string;
  zh: string;
  es: string;
  de: string;
  fr: string;
  hi: string;
  pt: string;
};

export const COUNTRIES: CountryEntry[] = [
  { code: 'AF', en: 'Afghanistan', zh: '阿富汗', es: 'Afganistán', de: 'Afghanistan', fr: 'Afghanistan', hi: 'अफ़ग़ानिस्तान', pt: 'Afeganistão' },
  { code: 'AL', en: 'Albania', zh: '阿尔巴尼亚', es: 'Albania', de: 'Albanien', fr: 'Albanie', hi: 'अल्बानिया', pt: 'Albânia' },
  { code: 'DZ', en: 'Algeria', zh: '阿尔及利亚', es: 'Argelia', de: 'Algerien', fr: 'Algérie', hi: 'अल्जीरिया', pt: 'Argélia' },
  { code: 'AD', en: 'Andorra', zh: '安道尔', es: 'Andorra', de: 'Andorra', fr: 'Andorre', hi: 'अंडोरा', pt: 'Andorra' },
  { code: 'AO', en: 'Angola', zh: '安哥拉', es: 'Angola', de: 'Angola', fr: 'Angola', hi: 'अंगोला', pt: 'Angola' },
  { code: 'AG', en: 'Antigua and Barbuda', zh: '安提瓜和巴布达', es: 'Antigua y Barbuda', de: 'Antigua und Barbuda', fr: 'Antigua-et-Barbuda', hi: 'एंटीगुआ और बारबुडा', pt: 'Antígua e Barbuda' },
  { code: 'AR', en: 'Argentina', zh: '阿根廷', es: 'Argentina', de: 'Argentinien', fr: 'Argentine', hi: 'अर्जेंटीना', pt: 'Argentina' },
  { code: 'AM', en: 'Armenia', zh: '亚美尼亚', es: 'Armenia', de: 'Armenien', fr: 'Arménie', hi: 'आर्मेनिया', pt: 'Armênia' },
  { code: 'AU', en: 'Australia', zh: '澳大利亚', es: 'Australia', de: 'Australien', fr: 'Australie', hi: 'ऑस्ट्रेलिया', pt: 'Austrália' },
  { code: 'AT', en: 'Austria', zh: '奥地利', es: 'Austria', de: 'Österreich', fr: 'Autriche', hi: 'ऑस्ट्रिया', pt: 'Áustria' },
  { code: 'AZ', en: 'Azerbaijan', zh: '阿塞拜疆', es: 'Azerbaiyán', de: 'Aserbaidschan', fr: 'Azerbaïdjan', hi: 'अज़रबैजान', pt: 'Azerbaijão' },
  { code: 'BS', en: 'Bahamas', zh: '巴哈马', es: 'Bahamas', de: 'Bahamas', fr: 'Bahamas', hi: 'बहामास', pt: 'Bahamas' },
  { code: 'BH', en: 'Bahrain', zh: '巴林', es: 'Baréin', de: 'Bahrain', fr: 'Bahreïn', hi: 'बहरीन', pt: 'Bahrein' },
  { code: 'BD', en: 'Bangladesh', zh: '孟加拉国', es: 'Bangladés', de: 'Bangladesch', fr: 'Bangladesh', hi: 'बांग्लादेश', pt: 'Bangladesh' },
  { code: 'BB', en: 'Barbados', zh: '巴巴多斯', es: 'Barbados', de: 'Barbados', fr: 'Barbade', hi: 'बार्बाडोस', pt: 'Barbados' },
  { code: 'BY', en: 'Belarus', zh: '白俄罗斯', es: 'Bielorrusia', de: 'Belarus', fr: 'Biélorussie', hi: 'बेलारूस', pt: 'Bielorrússia' },
  { code: 'BE', en: 'Belgium', zh: '比利时', es: 'Bélgica', de: 'Belgien', fr: 'Belgique', hi: 'बेल्जियम', pt: 'Bélgica' },
  { code: 'BZ', en: 'Belize', zh: '伯利兹', es: 'Belice', de: 'Belize', fr: 'Belize', hi: 'बेलीज़', pt: 'Belize' },
  { code: 'BJ', en: 'Benin', zh: '贝宁', es: 'Benín', de: 'Benin', fr: 'Bénin', hi: 'बेनिन', pt: 'Benim' },
  { code: 'BT', en: 'Bhutan', zh: '不丹', es: 'Bután', de: 'Bhutan', fr: 'Bhoutan', hi: 'भूटान', pt: 'Butão' },
  { code: 'BO', en: 'Bolivia', zh: '玻利维亚', es: 'Bolivia', de: 'Bolivien', fr: 'Bolivie', hi: 'बोलीविया', pt: 'Bolívia' },
  { code: 'BA', en: 'Bosnia and Herzegovina', zh: '波黑', es: 'Bosnia y Herzegovina', de: 'Bosnien und Herzegowina', fr: 'Bosnie-Herzégovine', hi: 'बोस्निया और हर्ज़ेगोविना', pt: 'Bósnia e Herzegovina' },
  { code: 'BW', en: 'Botswana', zh: '博茨瓦纳', es: 'Botsuana', de: 'Botswana', fr: 'Botswana', hi: 'बोत्स्वाना', pt: 'Botswana' },
  { code: 'BR', en: 'Brazil', zh: '巴西', es: 'Brasil', de: 'Brasilien', fr: 'Brésil', hi: 'ब्राज़ील', pt: 'Brasil' },
  { code: 'BN', en: 'Brunei', zh: '文莱', es: 'Brunéi', de: 'Brunei', fr: 'Brunéi', hi: 'ब्रुनेई', pt: 'Brunei' },
  { code: 'BG', en: 'Bulgaria', zh: '保加利亚', es: 'Bulgaria', de: 'Bulgarien', fr: 'Bulgarie', hi: 'बुल्गारिया', pt: 'Bulgária' },
  { code: 'BF', en: 'Burkina Faso', zh: '布基纳法索', es: 'Burkina Faso', de: 'Burkina Faso', fr: 'Burkina Faso', hi: 'बुर्किना फासो', pt: 'Burkina Faso' },
  { code: 'BI', en: 'Burundi', zh: '布隆迪', es: 'Burundi', de: 'Burundi', fr: 'Burundi', hi: 'बुरुंडी', pt: 'Burundi' },
  { code: 'CV', en: 'Cabo Verde', zh: '佛得角', es: 'Cabo Verde', de: 'Kap Verde', fr: 'Cap-Vert', hi: 'केप वर्डे', pt: 'Cabo Verde' },
  { code: 'KH', en: 'Cambodia', zh: '柬埔寨', es: 'Camboya', de: 'Kambodscha', fr: 'Cambodge', hi: 'कंबोडिया', pt: 'Camboja' },
  { code: 'CM', en: 'Cameroon', zh: '喀麦隆', es: 'Camerún', de: 'Kamerun', fr: 'Cameroun', hi: 'कैमरून', pt: 'Camarões' },
  { code: 'CA', en: 'Canada', zh: '加拿大', es: 'Canadá', de: 'Kanada', fr: 'Canada', hi: 'कनाडा', pt: 'Canadá' },
  { code: 'CF', en: 'Central African Republic', zh: '中非共和国', es: 'República Centroafricana', de: 'Zentralafrikanische Republik', fr: 'République centrafricaine', hi: 'मध्य अफ्रीकी गणराज्य', pt: 'República Centro-Africana' },
  { code: 'TD', en: 'Chad', zh: '乍得', es: 'Chad', de: 'Tschad', fr: 'Tchad', hi: 'चाड', pt: 'Chade' },
  { code: 'CL', en: 'Chile', zh: '智利', es: 'Chile', de: 'Chile', fr: 'Chili', hi: 'चिली', pt: 'Chile' },
  { code: 'CN', en: 'China', zh: '中国', es: 'China', de: 'China', fr: 'Chine', hi: 'चीन', pt: 'China' },
  { code: 'CO', en: 'Colombia', zh: '哥伦比亚', es: 'Colombia', de: 'Kolumbien', fr: 'Colombie', hi: 'कोलंबिया', pt: 'Colômbia' },
  { code: 'KM', en: 'Comoros', zh: '科摩罗', es: 'Comoras', de: 'Komoren', fr: 'Comores', hi: 'कोमोरोस', pt: 'Comores' },
  { code: 'CG', en: 'Congo', zh: '刚果共和国', es: 'Congo', de: 'Kongo', fr: 'Congo', hi: 'कांगो', pt: 'Congo' },
  { code: 'CD', en: 'Congo (DRC)', zh: '刚果民主共和国', es: 'Congo (RDC)', de: 'Kongo (DRK)', fr: 'Congo (RDC)', hi: 'कांगो (डीआरसी)', pt: 'Congo (RDC)' },
  { code: 'CR', en: 'Costa Rica', zh: '哥斯达黎加', es: 'Costa Rica', de: 'Costa Rica', fr: 'Costa Rica', hi: 'कोस्टा रिका', pt: 'Costa Rica' },
  { code: 'CI', en: 'Côte d\'Ivoire', zh: '科特迪瓦', es: 'Costa de Marfil', de: 'Elfenbeinküste', fr: 'Côte d\'Ivoire', hi: 'कोत दीव्वार', pt: 'Costa do Marfim' },
  { code: 'HR', en: 'Croatia', zh: '克罗地亚', es: 'Croacia', de: 'Kroatien', fr: 'Croatie', hi: 'क्रोएशिया', pt: 'Croácia' },
  { code: 'CU', en: 'Cuba', zh: '古巴', es: 'Cuba', de: 'Kuba', fr: 'Cuba', hi: 'क्यूबा', pt: 'Cuba' },
  { code: 'CY', en: 'Cyprus', zh: '塞浦路斯', es: 'Chipre', de: 'Zypern', fr: 'Chypre', hi: 'साइप्रस', pt: 'Chipre' },
  { code: 'CZ', en: 'Czech Republic', zh: '捷克共和国', es: 'República Checa', de: 'Tschechien', fr: 'République tchèque', hi: 'चेक गणराज्य', pt: 'República Tcheca' },
  { code: 'DK', en: 'Denmark', zh: '丹麦', es: 'Dinamarca', de: 'Dänemark', fr: 'Danemark', hi: 'डेनमार्क', pt: 'Dinamarca' },
  { code: 'DJ', en: 'Djibouti', zh: '吉布提', es: 'Yibuti', de: 'Dschibuti', fr: 'Djibouti', hi: 'जिबूती', pt: 'Djibuti' },
  { code: 'DM', en: 'Dominica', zh: '多米尼克', es: 'Dominica', de: 'Dominica', fr: 'Dominique', hi: 'डोमिनिका', pt: 'Dominica' },
  { code: 'DO', en: 'Dominican Republic', zh: '多米尼加共和国', es: 'República Dominicana', de: 'Dominikanische Republik', fr: 'République dominicaine', hi: 'डोमिनिकन गणराज्य', pt: 'República Dominicana' },
  { code: 'EC', en: 'Ecuador', zh: '厄瓜多尔', es: 'Ecuador', de: 'Ecuador', fr: 'Équateur', hi: 'इक्वाडोर', pt: 'Equador' },
  { code: 'EG', en: 'Egypt', zh: '埃及', es: 'Egipto', de: 'Ägypten', fr: 'Égypte', hi: 'मिस्र', pt: 'Egito' },
  { code: 'SV', en: 'El Salvador', zh: '萨尔瓦多', es: 'El Salvador', de: 'El Salvador', fr: 'Salvador', hi: 'अल सल्वाडोर', pt: 'El Salvador' },
  { code: 'GQ', en: 'Equatorial Guinea', zh: '赤道几内亚', es: 'Guinea Ecuatorial', de: 'Äquatorialguinea', fr: 'Guinée équatoriale', hi: 'भूमध्यरेखीय गिनी', pt: 'Guiné Equatorial' },
  { code: 'ER', en: 'Eritrea', zh: '厄立特里亚', es: 'Eritrea', de: 'Eritrea', fr: 'Érythrée', hi: 'इरिट्रिया', pt: 'Eritreia' },
  { code: 'EE', en: 'Estonia', zh: '爱沙尼亚', es: 'Estonia', de: 'Estland', fr: 'Estonie', hi: 'एस्टोनिया', pt: 'Estônia' },
  { code: 'SZ', en: 'Eswatini', zh: '斯威士兰', es: 'Esuatini', de: 'Eswatini', fr: 'Eswatini', hi: 'एस्वातीनी', pt: 'Eswatini' },
  { code: 'ET', en: 'Ethiopia', zh: '埃塞俄比亚', es: 'Etiopía', de: 'Äthiopien', fr: 'Éthiopie', hi: 'इथियोपिया', pt: 'Etiópia' },
  { code: 'FJ', en: 'Fiji', zh: '斐济', es: 'Fiyi', de: 'Fidschi', fr: 'Fidji', hi: 'फिजी', pt: 'Fiji' },
  { code: 'FI', en: 'Finland', zh: '芬兰', es: 'Finlandia', de: 'Finnland', fr: 'Finlande', hi: 'फिनलैंड', pt: 'Finlândia' },
  { code: 'FR', en: 'France', zh: '法国', es: 'Francia', de: 'Frankreich', fr: 'France', hi: 'फ्रांस', pt: 'França' },
  { code: 'GA', en: 'Gabon', zh: '加蓬', es: 'Gabón', de: 'Gabun', fr: 'Gabon', hi: 'गैबन', pt: 'Gabão' },
  { code: 'GM', en: 'Gambia', zh: '冈比亚', es: 'Gambia', de: 'Gambia', fr: 'Gambie', hi: 'गांबिया', pt: 'Gâmbia' },
  { code: 'GE', en: 'Georgia', zh: '格鲁吉亚', es: 'Georgia', de: 'Georgien', fr: 'Géorgie', hi: 'जॉर्जिया', pt: 'Geórgia' },
  { code: 'DE', en: 'Germany', zh: '德国', es: 'Alemania', de: 'Deutschland', fr: 'Allemagne', hi: 'जर्मनी', pt: 'Alemanha' },
  { code: 'GH', en: 'Ghana', zh: '加纳', es: 'Ghana', de: 'Ghana', fr: 'Ghana', hi: 'घाना', pt: 'Gana' },
  { code: 'GR', en: 'Greece', zh: '希腊', es: 'Grecia', de: 'Griechenland', fr: 'Grèce', hi: 'ग्रीस', pt: 'Grécia' },
  { code: 'GD', en: 'Grenada', zh: '格林纳达', es: 'Granada', de: 'Grenada', fr: 'Grenade', hi: 'ग्रेनाडा', pt: 'Granada' },
  { code: 'GT', en: 'Guatemala', zh: '危地马拉', es: 'Guatemala', de: 'Guatemala', fr: 'Guatemala', hi: 'ग्वाटेमाला', pt: 'Guatemala' },
  { code: 'GN', en: 'Guinea', zh: '几内亚', es: 'Guinea', de: 'Guinea', fr: 'Guinée', hi: 'गिनी', pt: 'Guiné' },
  { code: 'GW', en: 'Guinea-Bissau', zh: '几内亚比绍', es: 'Guinea-Bisáu', de: 'Guinea-Bissau', fr: 'Guinée-Bissau', hi: 'गिनी-बिसाऊ', pt: 'Guiné-Bissau' },
  { code: 'GY', en: 'Guyana', zh: '圭亚那', es: 'Guyana', de: 'Guyana', fr: 'Guyana', hi: 'गुयाना', pt: 'Guiana' },
  { code: 'HT', en: 'Haiti', zh: '海地', es: 'Haití', de: 'Haiti', fr: 'Haïti', hi: 'हैती', pt: 'Haiti' },
  { code: 'HN', en: 'Honduras', zh: '洪都拉斯', es: 'Honduras', de: 'Honduras', fr: 'Honduras', hi: 'होंडुरास', pt: 'Honduras' },
  { code: 'HU', en: 'Hungary', zh: '匈牙利', es: 'Hungría', de: 'Ungarn', fr: 'Hongrie', hi: 'हंगरी', pt: 'Hungria' },
  { code: 'IS', en: 'Iceland', zh: '冰岛', es: 'Islandia', de: 'Island', fr: 'Islande', hi: 'आइसलैंड', pt: 'Islândia' },
  { code: 'IN', en: 'India', zh: '印度', es: 'India', de: 'Indien', fr: 'Inde', hi: 'भारत', pt: 'Índia' },
  { code: 'ID', en: 'Indonesia', zh: '印度尼西亚', es: 'Indonesia', de: 'Indonesien', fr: 'Indonésie', hi: 'इंडोनेशिया', pt: 'Indonésia' },
  { code: 'IR', en: 'Iran', zh: '伊朗', es: 'Irán', de: 'Iran', fr: 'Iran', hi: 'ईरान', pt: 'Irã' },
  { code: 'IQ', en: 'Iraq', zh: '伊拉克', es: 'Irak', de: 'Irak', fr: 'Irak', hi: 'इराक', pt: 'Iraque' },
  { code: 'IE', en: 'Ireland', zh: '爱尔兰', es: 'Irlanda', de: 'Irland', fr: 'Irlande', hi: 'आयरलैंड', pt: 'Irlanda' },
  { code: 'IL', en: 'Israel', zh: '以色列', es: 'Israel', de: 'Israel', fr: 'Israël', hi: 'इज़राइल', pt: 'Israel' },
  { code: 'IT', en: 'Italy', zh: '意大利', es: 'Italia', de: 'Italien', fr: 'Italie', hi: 'इटली', pt: 'Itália' },
  { code: 'JM', en: 'Jamaica', zh: '牙买加', es: 'Jamaica', de: 'Jamaika', fr: 'Jamaïque', hi: 'जमैका', pt: 'Jamaica' },
  { code: 'JP', en: 'Japan', zh: '日本', es: 'Japón', de: 'Japan', fr: 'Japon', hi: 'जापान', pt: 'Japão' },
  { code: 'JO', en: 'Jordan', zh: '约旦', es: 'Jordania', de: 'Jordanien', fr: 'Jordanie', hi: 'जॉर्डन', pt: 'Jordânia' },
  { code: 'KZ', en: 'Kazakhstan', zh: '哈萨克斯坦', es: 'Kazajistán', de: 'Kasachstan', fr: 'Kazakhstan', hi: 'कज़ाखस्तान', pt: 'Cazaquistão' },
  { code: 'KE', en: 'Kenya', zh: '肯尼亚', es: 'Kenia', de: 'Kenia', fr: 'Kenya', hi: 'केन्या', pt: 'Quênia' },
  { code: 'KI', en: 'Kiribati', zh: '基里巴斯', es: 'Kiribati', de: 'Kiribati', fr: 'Kiribati', hi: 'किरिबाती', pt: 'Kiribati' },
  { code: 'KP', en: 'Korea (North)', zh: '朝鲜', es: 'Corea del Norte', de: 'Nordkorea', fr: 'Corée du Nord', hi: 'उत्तर कोरिया', pt: 'Coreia do Norte' },
  { code: 'KR', en: 'Korea (South)', zh: '韩国', es: 'Corea del Sur', de: 'Südkorea', fr: 'Corée du Sud', hi: 'दक्षिण कोरिया', pt: 'Coreia do Sul' },
  { code: 'KW', en: 'Kuwait', zh: '科威特', es: 'Kuwait', de: 'Kuwait', fr: 'Koweït', hi: 'कुवैत', pt: 'Kuwait' },
  { code: 'KG', en: 'Kyrgyzstan', zh: '吉尔吉斯斯坦', es: 'Kirguistán', de: 'Kirgisistan', fr: 'Kirghizistan', hi: 'किर्गिस्तान', pt: 'Quirguistão' },
  { code: 'LA', en: 'Laos', zh: '老挝', es: 'Laos', de: 'Laos', fr: 'Laos', hi: 'लाओस', pt: 'Laos' },
  { code: 'LV', en: 'Latvia', zh: '拉脱维亚', es: 'Letonia', de: 'Lettland', fr: 'Lettonie', hi: 'लात्विया', pt: 'Letônia' },
  { code: 'LB', en: 'Lebanon', zh: '黎巴嫩', es: 'Líbano', de: 'Libanon', fr: 'Liban', hi: 'लेबनान', pt: 'Líbano' },
  { code: 'LS', en: 'Lesotho', zh: '莱索托', es: 'Lesoto', de: 'Lesotho', fr: 'Lesotho', hi: 'लेसोथो', pt: 'Lesoto' },
  { code: 'LR', en: 'Liberia', zh: '利比里亚', es: 'Liberia', de: 'Liberia', fr: 'Libéria', hi: 'लाइबेरिया', pt: 'Libéria' },
  { code: 'LY', en: 'Libya', zh: '利比亚', es: 'Libia', de: 'Libyen', fr: 'Libye', hi: 'लीबिया', pt: 'Líbia' },
  { code: 'LI', en: 'Liechtenstein', zh: '列支敦士登', es: 'Liechtenstein', de: 'Liechtenstein', fr: 'Liechtenstein', hi: 'लिकटेंस्टाइन', pt: 'Liechtenstein' },
  { code: 'LT', en: 'Lithuania', zh: '立陶宛', es: 'Lituania', de: 'Litauen', fr: 'Lituanie', hi: 'लिथुआनिया', pt: 'Lituânia' },
  { code: 'LU', en: 'Luxembourg', zh: '卢森堡', es: 'Luxemburgo', de: 'Luxemburg', fr: 'Luxembourg', hi: 'लक्ज़मबर्ग', pt: 'Luxemburgo' },
  { code: 'MG', en: 'Madagascar', zh: '马达加斯加', es: 'Madagascar', de: 'Madagaskar', fr: 'Madagascar', hi: 'मेडागास्कर', pt: 'Madagascar' },
  { code: 'MW', en: 'Malawi', zh: '马拉维', es: 'Malaui', de: 'Malawi', fr: 'Malawi', hi: 'मलावी', pt: 'Malawi' },
  { code: 'MY', en: 'Malaysia', zh: '马来西亚', es: 'Malasia', de: 'Malaysia', fr: 'Malaisie', hi: 'मलेशिया', pt: 'Malásia' },
  { code: 'MV', en: 'Maldives', zh: '马尔代夫', es: 'Maldivas', de: 'Malediven', fr: 'Maldives', hi: 'मालदीव', pt: 'Maldivas' },
  { code: 'ML', en: 'Mali', zh: '马里', es: 'Malí', de: 'Mali', fr: 'Mali', hi: 'माली', pt: 'Mali' },
  { code: 'MT', en: 'Malta', zh: '马耳他', es: 'Malta', de: 'Malta', fr: 'Malte', hi: 'माल्टा', pt: 'Malta' },
  { code: 'MH', en: 'Marshall Islands', zh: '马绍尔群岛', es: 'Islas Marshall', de: 'Marshallinseln', fr: 'Îles Marshall', hi: 'मार्शल द्वीप', pt: 'Ilhas Marshall' },
  { code: 'MR', en: 'Mauritania', zh: '毛里塔尼亚', es: 'Mauritania', de: 'Mauretanien', fr: 'Mauritanie', hi: 'मॉरिटानिया', pt: 'Mauritânia' },
  { code: 'MU', en: 'Mauritius', zh: '毛里求斯', es: 'Mauricio', de: 'Mauritius', fr: 'Maurice', hi: 'मॉरीशस', pt: 'Maurício' },
  { code: 'MX', en: 'Mexico', zh: '墨西哥', es: 'México', de: 'Mexiko', fr: 'Mexique', hi: 'मेक्सिको', pt: 'México' },
  { code: 'FM', en: 'Micronesia', zh: '密克罗尼西亚', es: 'Micronesia', de: 'Mikronesien', fr: 'Micronésie', hi: 'माइक्रोनेशिया', pt: 'Micronésia' },
  { code: 'MD', en: 'Moldova', zh: '摩尔多瓦', es: 'Moldavia', de: 'Moldau', fr: 'Moldavie', hi: 'मोल्दोवा', pt: 'Moldávia' },
  { code: 'MC', en: 'Monaco', zh: '摩纳哥', es: 'Mónaco', de: 'Monaco', fr: 'Monaco', hi: 'मोनाको', pt: 'Mônaco' },
  { code: 'MN', en: 'Mongolia', zh: '蒙古', es: 'Mongolia', de: 'Mongolei', fr: 'Mongolie', hi: 'मंगोलिया', pt: 'Mongólia' },
  { code: 'ME', en: 'Montenegro', zh: '黑山', es: 'Montenegro', de: 'Montenegro', fr: 'Monténégro', hi: 'मोंटेनेग्रो', pt: 'Montenegro' },
  { code: 'MA', en: 'Morocco', zh: '摩洛哥', es: 'Marruecos', de: 'Marokko', fr: 'Maroc', hi: 'मोरक्को', pt: 'Marrocos' },
  { code: 'MZ', en: 'Mozambique', zh: '莫桑比克', es: 'Mozambique', de: 'Mosambik', fr: 'Mozambique', hi: 'मोज़ाम्बिक', pt: 'Moçambique' },
  { code: 'MM', en: 'Myanmar', zh: '缅甸', es: 'Myanmar', de: 'Myanmar', fr: 'Myanmar', hi: 'म्यांमार', pt: 'Myanmar' },
  { code: 'NA', en: 'Namibia', zh: '纳米比亚', es: 'Namibia', de: 'Namibia', fr: 'Namibie', hi: 'नामीबिया', pt: 'Namíbia' },
  { code: 'NR', en: 'Nauru', zh: '瑙鲁', es: 'Nauru', de: 'Nauru', fr: 'Nauru', hi: 'नौरु', pt: 'Nauru' },
  { code: 'NP', en: 'Nepal', zh: '尼泊尔', es: 'Nepal', de: 'Nepal', fr: 'Népal', hi: 'नेपाल', pt: 'Nepal' },
  { code: 'NL', en: 'Netherlands', zh: '荷兰', es: 'Países Bajos', de: 'Niederlande', fr: 'Pays-Bas', hi: 'नीदरलैंड', pt: 'Países Baixos' },
  { code: 'NZ', en: 'New Zealand', zh: '新西兰', es: 'Nueva Zelanda', de: 'Neuseeland', fr: 'Nouvelle-Zélande', hi: 'न्यूज़ीलैंड', pt: 'Nova Zelândia' },
  { code: 'NI', en: 'Nicaragua', zh: '尼加拉瓜', es: 'Nicaragua', de: 'Nicaragua', fr: 'Nicaragua', hi: 'निकारागुआ', pt: 'Nicarágua' },
  { code: 'NE', en: 'Niger', zh: '尼日尔', es: 'Níger', de: 'Niger', fr: 'Niger', hi: 'नाइजर', pt: 'Níger' },
  { code: 'NG', en: 'Nigeria', zh: '尼日利亚', es: 'Nigeria', de: 'Nigeria', fr: 'Nigéria', hi: 'नाइजीरिया', pt: 'Nigéria' },
  { code: 'MK', en: 'North Macedonia', zh: '北马其顿', es: 'Macedonia del Norte', de: 'Nordmazedonien', fr: 'Macédoine du Nord', hi: 'उत्तर मैसेडोनिया', pt: 'Macedônia do Norte' },
  { code: 'NO', en: 'Norway', zh: '挪威', es: 'Noruega', de: 'Norwegen', fr: 'Norvège', hi: 'नॉर्वे', pt: 'Noruega' },
  { code: 'OM', en: 'Oman', zh: '阿曼', es: 'Omán', de: 'Oman', fr: 'Oman', hi: 'ओमान', pt: 'Omã' },
  { code: 'PK', en: 'Pakistan', zh: '巴基斯坦', es: 'Pakistán', de: 'Pakistan', fr: 'Pakistan', hi: 'पाकिस्तान', pt: 'Paquistão' },
  { code: 'PW', en: 'Palau', zh: '帕劳', es: 'Palaos', de: 'Palau', fr: 'Palaos', hi: 'पलाऊ', pt: 'Palau' },
  { code: 'PA', en: 'Panama', zh: '巴拿马', es: 'Panamá', de: 'Panama', fr: 'Panama', hi: 'पनामा', pt: 'Panamá' },
  { code: 'PG', en: 'Papua New Guinea', zh: '巴布亚新几内亚', es: 'Papúa Nueva Guinea', de: 'Papua-Neuguinea', fr: 'Papouasie-Nouvelle-Guinée', hi: 'पापुआ न्यू गिनी', pt: 'Papua Nova Guiné' },
  { code: 'PY', en: 'Paraguay', zh: '巴拉圭', es: 'Paraguay', de: 'Paraguay', fr: 'Paraguay', hi: 'पराग्वे', pt: 'Paraguai' },
  { code: 'PE', en: 'Peru', zh: '秘鲁', es: 'Perú', de: 'Peru', fr: 'Pérou', hi: 'पेरू', pt: 'Peru' },
  { code: 'PH', en: 'Philippines', zh: '菲律宾', es: 'Filipinas', de: 'Philippinen', fr: 'Philippines', hi: 'फिलीपींस', pt: 'Filipinas' },
  { code: 'PL', en: 'Poland', zh: '波兰', es: 'Polonia', de: 'Polen', fr: 'Pologne', hi: 'पोलैंड', pt: 'Polônia' },
  { code: 'PT', en: 'Portugal', zh: '葡萄牙', es: 'Portugal', de: 'Portugal', fr: 'Portugal', hi: 'पुर्तगाल', pt: 'Portugal' },
  { code: 'QA', en: 'Qatar', zh: '卡塔尔', es: 'Catar', de: 'Katar', fr: 'Qatar', hi: 'क़तर', pt: 'Catar' },
  { code: 'RO', en: 'Romania', zh: '罗马尼亚', es: 'Rumanía', de: 'Rumänien', fr: 'Roumanie', hi: 'रोमानिया', pt: 'Romênia' },
  { code: 'RU', en: 'Russia', zh: '俄罗斯', es: 'Rusia', de: 'Russland', fr: 'Russie', hi: 'रूस', pt: 'Rússia' },
  { code: 'RW', en: 'Rwanda', zh: '卢旺达', es: 'Ruanda', de: 'Ruanda', fr: 'Rwanda', hi: 'रवांडा', pt: 'Ruanda' },
  { code: 'KN', en: 'Saint Kitts and Nevis', zh: '圣基茨和尼维斯', es: 'San Cristóbal y Nieves', de: 'St. Kitts und Nevis', fr: 'Saint-Kitts-et-Nevis', hi: 'सेंट किट्स और नेविस', pt: 'São Cristóvão e Nevis' },
  { code: 'LC', en: 'Saint Lucia', zh: '圣卢西亚', es: 'Santa Lucía', de: 'St. Lucia', fr: 'Sainte-Lucie', hi: 'सेंट लूसिया', pt: 'Santa Lúcia' },
  { code: 'VC', en: 'Saint Vincent and the Grenadines', zh: '圣文森特和格林纳丁斯', es: 'San Vicente y las Granadinas', de: 'St. Vincent und die Grenadinen', fr: 'Saint-Vincent-et-les-Grenadines', hi: 'सेंट विंसेंट और ग्रेनाडाइन्स', pt: 'São Vicente e Granadinas' },
  { code: 'WS', en: 'Samoa', zh: '萨摩亚', es: 'Samoa', de: 'Samoa', fr: 'Samoa', hi: 'समोआ', pt: 'Samoa' },
  { code: 'SM', en: 'San Marino', zh: '圣马力诺', es: 'San Marino', de: 'San Marino', fr: 'Saint-Marin', hi: 'सान मारिनो', pt: 'San Marino' },
  { code: 'ST', en: 'Sao Tome and Principe', zh: '圣多美和普林西比', es: 'Santo Tomé y Príncipe', de: 'São Tomé und Príncipe', fr: 'Sao Tomé-et-Principe', hi: 'साओ टोमे और प्रिंसिपे', pt: 'São Tomé e Príncipe' },
  { code: 'SA', en: 'Saudi Arabia', zh: '沙特阿拉伯', es: 'Arabia Saudita', de: 'Saudi-Arabien', fr: 'Arabie saoudite', hi: 'सऊदी अरब', pt: 'Arábia Saudita' },
  { code: 'SN', en: 'Senegal', zh: '塞内加尔', es: 'Senegal', de: 'Senegal', fr: 'Sénégal', hi: 'सेनेगल', pt: 'Senegal' },
  { code: 'RS', en: 'Serbia', zh: '塞尔维亚', es: 'Serbia', de: 'Serbien', fr: 'Serbie', hi: 'सर्बिया', pt: 'Sérvia' },
  { code: 'SC', en: 'Seychelles', zh: '塞舌尔', es: 'Seychelles', de: 'Seychellen', fr: 'Seychelles', hi: 'सेशेल्स', pt: 'Seicheles' },
  { code: 'SL', en: 'Sierra Leone', zh: '塞拉利昂', es: 'Sierra Leona', de: 'Sierra Leone', fr: 'Sierra Leone', hi: 'सिएरा लियोन', pt: 'Serra Leoa' },
  { code: 'SG', en: 'Singapore', zh: '新加坡', es: 'Singapur', de: 'Singapur', fr: 'Singapour', hi: 'सिंगापुर', pt: 'Singapura' },
  { code: 'SK', en: 'Slovakia', zh: '斯洛伐克', es: 'Eslovaquia', de: 'Slowakei', fr: 'Slovaquie', hi: 'स्लोवाकिया', pt: 'Eslováquia' },
  { code: 'SI', en: 'Slovenia', zh: '斯洛文尼亚', es: 'Eslovenia', de: 'Slowenien', fr: 'Slovénie', hi: 'स्लोवेनिया', pt: 'Eslovênia' },
  { code: 'SB', en: 'Solomon Islands', zh: '所罗门群岛', es: 'Islas Salomón', de: 'Salomonen', fr: 'Îles Salomon', hi: 'सोलोमन द्वीप', pt: 'Ilhas Salomão' },
  { code: 'SO', en: 'Somalia', zh: '索马里', es: 'Somalia', de: 'Somalia', fr: 'Somalie', hi: 'सोमालिया', pt: 'Somália' },
  { code: 'ZA', en: 'South Africa', zh: '南非', es: 'Sudáfrica', de: 'Südafrika', fr: 'Afrique du Sud', hi: 'दक्षिण अफ्रीका', pt: 'África do Sul' },
  { code: 'SS', en: 'South Sudan', zh: '南苏丹', es: 'Sudán del Sur', de: 'Südsudan', fr: 'Soudan du Sud', hi: 'दक्षिण सूडान', pt: 'Sudão do Sul' },
  { code: 'ES', en: 'Spain', zh: '西班牙', es: 'España', de: 'Spanien', fr: 'Espagne', hi: 'स्पेन', pt: 'Espanha' },
  { code: 'LK', en: 'Sri Lanka', zh: '斯里兰卡', es: 'Sri Lanka', de: 'Sri Lanka', fr: 'Sri Lanka', hi: 'श्रीलंका', pt: 'Sri Lanka' },
  { code: 'SD', en: 'Sudan', zh: '苏丹', es: 'Sudán', de: 'Sudan', fr: 'Soudan', hi: 'सूडान', pt: 'Sudão' },
  { code: 'SR', en: 'Suriname', zh: '苏里南', es: 'Surinam', de: 'Surinam', fr: 'Suriname', hi: 'सूरीनाम', pt: 'Suriname' },
  { code: 'SE', en: 'Sweden', zh: '瑞典', es: 'Suecia', de: 'Schweden', fr: 'Suède', hi: 'स्वीडन', pt: 'Suécia' },
  { code: 'CH', en: 'Switzerland', zh: '瑞士', es: 'Suiza', de: 'Schweiz', fr: 'Suisse', hi: 'स्विट्ज़रलैंड', pt: 'Suíça' },
  { code: 'SY', en: 'Syria', zh: '叙利亚', es: 'Siria', de: 'Syrien', fr: 'Syrie', hi: 'सीरिया', pt: 'Síria' },
  { code: 'TW', en: 'Taiwan', zh: '台湾', es: 'Taiwán', de: 'Taiwan', fr: 'Taïwan', hi: 'ताइवान', pt: 'Taiwan' },
  { code: 'TJ', en: 'Tajikistan', zh: '塔吉克斯坦', es: 'Tayikistán', de: 'Tadschikistan', fr: 'Tadjikistan', hi: 'ताजिकिस्तान', pt: 'Tajiquistão' },
  { code: 'TZ', en: 'Tanzania', zh: '坦桑尼亚', es: 'Tanzania', de: 'Tansania', fr: 'Tanzanie', hi: 'तंज़ानिया', pt: 'Tanzânia' },
  { code: 'TH', en: 'Thailand', zh: '泰国', es: 'Tailandia', de: 'Thailand', fr: 'Thaïlande', hi: 'थाईलैंड', pt: 'Tailândia' },
  { code: 'TL', en: 'Timor-Leste', zh: '东帝汶', es: 'Timor Oriental', de: 'Osttimor', fr: 'Timor oriental', hi: 'तिमोर-लेस्ते', pt: 'Timor-Leste' },
  { code: 'TG', en: 'Togo', zh: '多哥', es: 'Togo', de: 'Togo', fr: 'Togo', hi: 'टोगो', pt: 'Togo' },
  { code: 'TO', en: 'Tonga', zh: '汤加', es: 'Tonga', de: 'Tonga', fr: 'Tonga', hi: 'टोंगा', pt: 'Tonga' },
  { code: 'TT', en: 'Trinidad and Tobago', zh: '特立尼达和多巴哥', es: 'Trinidad y Tobago', de: 'Trinidad und Tobago', fr: 'Trinité-et-Tobago', hi: 'त्रिनिदाद और टोबैगो', pt: 'Trinidad e Tobago' },
  { code: 'TN', en: 'Tunisia', zh: '突尼斯', es: 'Túnez', de: 'Tunesien', fr: 'Tunisie', hi: 'ट्यूनीशिया', pt: 'Tunísia' },
  { code: 'TR', en: 'Turkey', zh: '土耳其', es: 'Turquía', de: 'Türkei', fr: 'Turquie', hi: 'तुर्की', pt: 'Turquia' },
  { code: 'TM', en: 'Turkmenistan', zh: '土库曼斯坦', es: 'Turkmenistán', de: 'Turkmenistan', fr: 'Turkménistan', hi: 'तुर्कमेनिस्तान', pt: 'Turcomenistão' },
  { code: 'TV', en: 'Tuvalu', zh: '图瓦卢', es: 'Tuvalu', de: 'Tuvalu', fr: 'Tuvalu', hi: 'टुवालु', pt: 'Tuvalu' },
  { code: 'UG', en: 'Uganda', zh: '乌干达', es: 'Uganda', de: 'Uganda', fr: 'Ouganda', hi: 'युगांडा', pt: 'Uganda' },
  { code: 'UA', en: 'Ukraine', zh: '乌克兰', es: 'Ucrania', de: 'Ukraine', fr: 'Ukraine', hi: 'यूक्रेन', pt: 'Ucrânia' },
  { code: 'AE', en: 'United Arab Emirates', zh: '阿拉伯联合酋长国', es: 'Emiratos Árabes Unidos', de: 'Vereinigte Arabische Emirate', fr: 'Émirats arabes unis', hi: 'संयुक्त अरब अमीरात', pt: 'Emirados Árabes Unidos' },
  { code: 'GB', en: 'United Kingdom', zh: '英国', es: 'Reino Unido', de: 'Vereinigtes Königreich', fr: 'Royaume-Uni', hi: 'यूनाइटेड किंगडम', pt: 'Reino Unido' },
  { code: 'US', en: 'United States', zh: '美国', es: 'Estados Unidos', de: 'Vereinigte Staaten', fr: 'États-Unis', hi: 'संयुक्त राज्य अमेरिका', pt: 'Estados Unidos' },
  { code: 'UY', en: 'Uruguay', zh: '乌拉圭', es: 'Uruguay', de: 'Uruguay', fr: 'Uruguay', hi: 'उरुग्वे', pt: 'Uruguai' },
  { code: 'UZ', en: 'Uzbekistan', zh: '乌兹别克斯坦', es: 'Uzbekistán', de: 'Usbekistan', fr: 'Ouzbékistan', hi: 'उज़्बेकिस्तान', pt: 'Uzbequistão' },
  { code: 'VU', en: 'Vanuatu', zh: '瓦努阿图', es: 'Vanuatu', de: 'Vanuatu', fr: 'Vanuatu', hi: 'वानुआतु', pt: 'Vanuatu' },
  { code: 'VA', en: 'Vatican City', zh: '梵蒂冈', es: 'Ciudad del Vaticano', de: 'Vatikanstadt', fr: 'Vatican', hi: 'वेटिकन सिटी', pt: 'Cidade do Vaticano' },
  { code: 'VE', en: 'Venezuela', zh: '委内瑞拉', es: 'Venezuela', de: 'Venezuela', fr: 'Venezuela', hi: 'वेनेज़ुएला', pt: 'Venezuela' },
  { code: 'VN', en: 'Vietnam', zh: '越南', es: 'Vietnam', de: 'Vietnam', fr: 'Vietnam', hi: 'वियतनाम', pt: 'Vietnã' },
  { code: 'YE', en: 'Yemen', zh: '也门', es: 'Yemen', de: 'Jemen', fr: 'Yémen', hi: 'यमन', pt: 'Iêmen' },
  { code: 'ZM', en: 'Zambia', zh: '赞比亚', es: 'Zambia', de: 'Sambia', fr: 'Zambie', hi: 'जाम्बिया', pt: 'Zâmbia' },
  { code: 'ZW', en: 'Zimbabwe', zh: '津巴布韦', es: 'Zimbabue', de: 'Simbabwe', fr: 'Zimbabwe', hi: 'ज़िम्बाब्वे', pt: 'Zimbábue' },
];

export type SupportedLang = 'en' | 'zh' | 'es' | 'de' | 'fr' | 'hi' | 'pt' | 'ja';

// Map from ISO code to ITU dial prefix
export const DIAL_CODES: Record<string, string> = {
  AF: '+93', AL: '+355', DZ: '+213', AD: '+376', AO: '+244', AG: '+1-268',
  AR: '+54', AM: '+374', AU: '+61', AT: '+43', AZ: '+994', BS: '+1-242',
  BH: '+973', BD: '+880', BB: '+1-246', BY: '+375', BE: '+32', BZ: '+501',
  BJ: '+229', BT: '+975', BO: '+591', BA: '+387', BW: '+267', BR: '+55',
  BN: '+673', BG: '+359', BF: '+226', BI: '+257', CV: '+238', KH: '+855',
  CM: '+237', CA: '+1', CF: '+236', TD: '+235', CL: '+56', CN: '+86',
  CO: '+57', KM: '+269', CG: '+242', CD: '+243', CR: '+506', CI: '+225',
  HR: '+385', CU: '+53', CY: '+357', CZ: '+420', DK: '+45', DJ: '+253',
  DM: '+1-767', DO: '+1-809', EC: '+593', EG: '+20', SV: '+503', GQ: '+240',
  ER: '+291', EE: '+372', SZ: '+268', ET: '+251', FJ: '+679', FI: '+358',
  FR: '+33', GA: '+241', GM: '+220', GE: '+995', DE: '+49', GH: '+233',
  GR: '+30', GD: '+1-473', GT: '+502', GN: '+224', GW: '+245', GY: '+592',
  HT: '+509', HN: '+504', HU: '+36', IS: '+354', IN: '+91', ID: '+62',
  IR: '+98', IQ: '+964', IE: '+353', IL: '+972', IT: '+39', JM: '+1-876',
  JP: '+81', JO: '+962', KZ: '+7', KE: '+254', KI: '+686', KP: '+850',
  KR: '+82', KW: '+965', KG: '+996', LA: '+856', LV: '+371', LB: '+961',
  LS: '+266', LR: '+231', LY: '+218', LI: '+423', LT: '+370', LU: '+352',
  MG: '+261', MW: '+265', MY: '+60', MV: '+960', ML: '+223', MT: '+356',
  MH: '+692', MR: '+222', MU: '+230', MX: '+52', FM: '+691', MD: '+373',
  MC: '+377', MN: '+976', ME: '+382', MA: '+212', MZ: '+258', MM: '+95',
  NA: '+264', NR: '+674', NP: '+977', NL: '+31', NZ: '+64', NI: '+505',
  NE: '+227', NG: '+234', MK: '+389', NO: '+47', OM: '+968', PK: '+92',
  PW: '+680', PA: '+507', PG: '+675', PY: '+595', PE: '+51', PH: '+63',
  PL: '+48', PT: '+351', QA: '+974', RO: '+40', RU: '+7', RW: '+250',
  KN: '+1-869', LC: '+1-758', VC: '+1-784', WS: '+685', SM: '+378',
  ST: '+239', SA: '+966', SN: '+221', RS: '+381', SC: '+248', SL: '+232',
  SG: '+65', SK: '+421', SI: '+386', SB: '+677', SO: '+252', ZA: '+27',
  SS: '+211', ES: '+34', LK: '+94', SD: '+249', SR: '+597', SE: '+46',
  CH: '+41', SY: '+963', TW: '+886', TJ: '+992', TZ: '+255', TH: '+66',
  TL: '+670', TG: '+228', TO: '+676', TT: '+1-868', TN: '+216', TR: '+90',
  TM: '+993', TV: '+688', UG: '+256', UA: '+380', AE: '+971', GB: '+44',
  US: '+1', UY: '+598', UZ: '+998', VU: '+678', VA: '+379', VE: '+58',
  VN: '+84', YE: '+967', ZM: '+260', ZW: '+263',
};

export function getSortedDialCodes(lang: SupportedLang): Array<{ code: string; dialCode: string; name: string }> {
  const key = lang === 'ja' ? 'en' : lang;
  return COUNTRIES
    .filter(c => DIAL_CODES[c.code])
    .map(c => ({ code: c.code, dialCode: DIAL_CODES[c.code], name: c[key] || c.en }))
    .sort((a, b) => a.name.localeCompare(b.name, key === 'zh' ? 'zh' : undefined));
}

export function getCountryName(code: string, lang: SupportedLang): string {
  const entry = COUNTRIES.find(c => c.code === code);
  if (!entry) return code;
  const key = lang === 'ja' ? 'en' : lang;
  return entry[key] || entry.en;
}

export function getSortedCountries(lang: SupportedLang): CountryEntry[] {
  const key = lang === 'ja' ? 'en' : lang;
  return [...COUNTRIES].sort((a, b) => a[key].localeCompare(b[key], key === 'zh' ? 'zh' : undefined));
}
